apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-aljt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-aljt
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-aljt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-aljt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-aljt
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uqvq-tenant/rhtap-demo-app/hacbs-test-project-aljt@sha256:9922023f707a610ed3a623416014ecda9f4f282fa0a31c0fe278ca3a63eda96a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
